version: '3'
services:
  web:
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'PUT YOUR EMAIL ADDRESS HERE <contact@domain.com>'
      PGADMIN_DEFAULT_PASSWORD: 'PUT YOUR PASSWORD HERE'
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'True'
      PGADMIN_CONFIG_LOGIN_BANNER: '"Authorised users only!"'
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    restart: always
    ports:
      - '8686:80'
