version: '3.6'

services:
    pgadmin4:
        image: 'dpage/pgadmin4:7.5'
        container_name: pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: 'PUT YOUR EMAIL ADDRESS HERE <contact@domain.com>'
            PGADMIN_DEFAULT_PASSWORD: 'PUT YOUR PASSWORD HERE'
            PGADMIN_LISTEN_PORT: 8432
            PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'True'
            PGADMIN_CONFIG_LOGIN_BANNER: '"Authorised users only!"'
            PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
            PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: 'False'
        restart: always
        volumes:
            - pgadmin4_data:/var/lib/pgadmin/pgadmin4.db
        network_mode: host

volumes:
    pgadmin4_data:
        name: pgadmin4_data
